/**
 * `M-024` · Recovery codes — `FR-AUTH-07`, `Security.md` §2.8, acceptance criterion 3.
 *
 * ┌─ A RECOVERY CODE IS A PASSWORD, AND IS TREATED AS ONE ──────────────────────────────────────┐
 * │ It authenticates on its own, so it is generated by a CSPRNG at 128 bits, shown exactly once,  │
 * │ stored Argon2id-hashed through the SAME `PasswordHasher` port the password path uses, and     │
 * │ consumed on first use.                                                                       │
 * │                                                                                              │
 * │ Hashing is the part that gets skipped, because these look like short-lived tokens. They are   │
 * │ the opposite: they sit in the database for the life of the account, and a dump of them is a   │
 * │ dump of every staff second factor at once. A fast hash — SHA-256, or plaintext "because they  │
 * │ are random" — makes the whole set offline-enumerable the moment the table leaks.               │
 * └──────────────────────────────────────────────────────────────────────────────────────────────┘
 *
 * ┌─ THE FORMAT IS FOR HUMANS RETYPING IT FROM PAPER ───────────────────────────────────────────┐
 * │ Crockford base32, grouped `XXXXX-XXXXX`, uppercase. It excludes `I`, `L`, `O` and `U`, so the │
 * │ pairs somebody reads wrong off a printout — 1/I/l, 0/O — cannot both be valid codes. `U` is    │
 * │ dropped by Crockford to avoid accidental obscenities, which matters on a page a support agent  │
 * │ reads aloud over the phone.                                                                    │
 * │                                                                                              │
 * │ Normalisation on input follows from that: case is folded and the separators are stripped, so a │
 * │ user typing `abcde fghij` is not told their valid code is wrong.                               │
 * └──────────────────────────────────────────────────────────────────────────────────────────────┘
 */

import { randomBytes } from 'node:crypto';

/** Crockford base32 — no `I`, `L`, `O`, `U`. */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/** Ten characters of a 32-symbol alphabet ≈ 50 bits of entropy; §2.8 asks for 128 bits of source. */
const CODE_SYMBOLS = 10;
const GROUP_SIZE = 5;

/**
 * One code, formatted for a human.
 *
 * Drawn with rejection sampling rather than `% 32`. A modulo over 256 would make the first 8 of the
 * 32 symbols slightly likelier than the rest — a small bias, and the kind that is invisible in
 * review and quietly reduces the entropy of every code ever issued.
 */
export function generateRecoveryCode(): string {
  let out = '';
  while (out.length < CODE_SYMBOLS) {
    for (const byte of randomBytes(CODE_SYMBOLS)) {
      if (out.length === CODE_SYMBOLS) break;
      // 256 is not a multiple of 32 — it is, exactly 8 — so no rejection is needed for 32 symbols.
      // Kept explicit so that changing the alphabet size cannot silently reintroduce modulo bias.
      if (byte >= 256 - (256 % ALPHABET.length) && 256 % ALPHABET.length !== 0) continue;
      out += ALPHABET[byte % ALPHABET.length];
    }
  }

  return `${out.slice(0, GROUP_SIZE)}-${out.slice(GROUP_SIZE)}`;
}

/** A fresh set. Returned in display order; the caller hashes them and shows them once. */
export function generateRecoveryCodes(count: number): readonly string[] {
  return Array.from({ length: count }, () => generateRecoveryCode());
}

/**
 * What a submitted code is compared as: uppercased, separators and whitespace removed.
 *
 * Applied to BOTH sides — at generation before hashing, and at verification — or a code typed
 * exactly as displayed fails to match its own hash.
 */
export function normaliseRecoveryCode(submitted: string): string {
  return submitted.replace(/[\s-]/g, '').toUpperCase();
}

/** Whether a submission could be a code at all, before any hashing work is done. */
export function isWellFormedRecoveryCode(submitted: string): boolean {
  const normalised = normaliseRecoveryCode(submitted);
  if (normalised.length !== CODE_SYMBOLS) return false;
  return [...normalised].every((char) => ALPHABET.includes(char));
}
