-- migration: 20260810190000_expand_seed_reference_cities
-- phase:            expand                     -- MG3
-- requirement:      BLK-21 RESOLVED (geography half), ADR-0042, NFR-DQ-06, C9.4, TM3,
--                   SeedStrategy.md §3.6, SEP1, RD2, RD4, RD5, ADR-0007
-- tables:           cities (12 rows) — INSERT only
-- rls:              NONE — GLOBAL reference on the closed §1.3 exemption list
-- grants:           unchanged. G-REF minus the write half; rows written by the migration role
-- append_only:      no UPDATE and no DELETE are granted to any application role
-- partitioned:      no
-- max_lock:         ROW EXCLUSIVE on a table holding zero rows
-- rewrite:          none
-- est_duration:     < 30 ms                                               -- MG11
-- backfill_job:     none. This IS the data.
-- rollback:         DELETE the twelve rows by their derived ids. gyms.city_id and branches.city_id
--                   reference them; both tables are empty
-- concurrent_steps: none. gix_cities__centroid already exists and indexes twelve rows instantly
-- reviewers:        two, one schema owner      -- MG8
-- docs:             docs/DECISION_LOG.md ADR-0042 · SeedStrategy.md §3.6 · PHASES.md BLK-21
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- GENERATED BY `pnpm ref:generate` FROM `prisma/reference/cities.csv`. DO NOT EDIT BY HAND.
--
-- ┌─ THE SLUGS ARE §3.6 VERBATIM; THE NAMES AND CENTROIDS ARE FACTS, NOT CHOICES ────────────────┐
-- │ §3.6 fixes twelve metro slugs, their GST state codes, `status = 'PLANNED'` and                │
-- │ `timezone = 'Asia/Kolkata'` for all twelve. It fixes no display `name` and no `centroid`,      │
-- │ and `Schema.md` §12.1 makes both `NOT NULL`. That gap is what `BLK-21` was about.               │
-- │                                                                                              │
-- │ It is a different KIND of gap from the amenity names, and that is why this half is safer      │
-- │ still. `mumbai` → *"Mumbai"* is not a product decision, and Mumbai's centroid is not a taste   │
-- │ question — it is a fact about the world. The four coordinates `Marketplace.md` §10.1 happens   │
-- │ to carry (Mumbai, Bengaluru, Pune, Hyderabad) match these to four decimal places, which is     │
-- │ corroboration rather than authority: that block is banner-marked `illustrative`.               │
-- └──────────────────────────────────────────────────────────────────────────────────────────────┘
--
-- ┌─ EVERY CITY IS `PLANNED`, AND NONE OF THEM IS THE LAUNCH CITY ───────────────────────────────┐
-- │ §3.6: *"`OQ-01` fixed the launch COUNTRY; the launch CITY is selected separately against the  │
-- │ `C9.4` criteria. Until then every Indian city is `PLANNED`."* Registered as open item `O-5`.   │
-- │ Nothing here promotes a city, and flipping one to `LIVE` is a `C9.4` gate decision with five   │
-- │ measurable criteria behind it — not a data edit.                                                │
-- └──────────────────────────────────────────────────────────────────────────────────────────────┘
--
-- ┌─ `ST_MakePoint` TAKES LONGITUDE FIRST ───────────────────────────────────────────────────────┐
-- │ The single easiest thing to get wrong in this file. Swapped, Mumbai lands in the Indian Ocean │
-- │ off Somalia — a valid point, on the right planet, that no "is this a geography" check would   │
-- │ catch. The CSV names its columns `latitude` and `longitude`, and the generator maps them, so   │
-- │ the swap has to be made deliberately rather than by ordering two anonymous numbers.             │
-- │                                                                                              │
-- │ `geography`, never `geometry` — ADR-0007. `gix_cities__centroid` is GiST and already exists.   │
-- └──────────────────────────────────────────────────────────────────────────────────────────────┘
--
-- No `ON CONFLICT`, per `RD5`. A duplicate under forward-only migrations means this ran twice.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

SET LOCAL lock_timeout       = '5s';    -- PM-8. first statement, always
SET LOCAL statement_timeout  = '300s';  -- PM-8. second statement, always


-- cities: 12 row(s), generated from cities.csv
INSERT INTO cities (id, country_code, name, slug, centroid, status, timezone) VALUES
  ('d0252ae4-d3a5-5bf9-9ced-9ee86399c8ec', 'IN', 'Ahmedabad', 'ahmedabad', ST_SetSRID(ST_MakePoint(72.5714, 23.0225), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('79f0a47b-2df2-5f9f-83e6-1bf1de75665d', 'IN', 'Bengaluru', 'bengaluru', ST_SetSRID(ST_MakePoint(77.5946, 12.9716), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('e8e4c1e3-079a-5f35-b3fc-1b7f75f8a38e', 'IN', 'Chandigarh', 'chandigarh', ST_SetSRID(ST_MakePoint(76.7794, 30.7333), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('f41330d7-82f9-5bfa-8534-7bef428b68fe', 'IN', 'Chennai', 'chennai', ST_SetSRID(ST_MakePoint(80.2707, 13.0827), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('f92e206a-5de1-5383-a864-3d8c8c909c0f', 'IN', 'Delhi', 'delhi', ST_SetSRID(ST_MakePoint(77.209, 28.6139), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('f8fc31e3-6d67-50d4-859e-a368939bb018', 'IN', 'Hyderabad', 'hyderabad', ST_SetSRID(ST_MakePoint(78.4867, 17.385), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('990d6bfa-ed87-53fe-840f-7c16fcc3f2fc', 'IN', 'Jaipur', 'jaipur', ST_SetSRID(ST_MakePoint(75.7873, 26.9124), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('dbc26b43-a857-5d5c-831c-bf5d2a0ce027', 'IN', 'Kolkata', 'kolkata', ST_SetSRID(ST_MakePoint(88.3639, 22.5726), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('cfd35a33-5dfe-5a1c-8c33-b691154826d3', 'IN', 'Lucknow', 'lucknow', ST_SetSRID(ST_MakePoint(80.9462, 26.8467), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('ae93b9ec-b171-5307-863e-2896905b4dc0', 'IN', 'Mumbai', 'mumbai', ST_SetSRID(ST_MakePoint(72.8777, 19.076), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('0cfa2233-7ca8-5457-9467-0de7a48438c6', 'IN', 'Pune', 'pune', ST_SetSRID(ST_MakePoint(73.8567, 18.5204), 4326)::geography, 'PLANNED', 'Asia/Kolkata'),
  ('f5a8ed90-4cd5-53c5-a0ce-9ec402f19fec', 'IN', 'Surat', 'surat', ST_SetSRID(ST_MakePoint(72.8311, 21.1702), 4326)::geography, 'PLANNED', 'Asia/Kolkata');
