/**
 * `M-024` · TOTP against RFC 6238's own numbers — `FR-AUTH-07`, `NFR-SEC-11`, `Security.md` §2.8.
 *
 * ═══════════════════════════════════════════════════════════════════════════════════════════
 * THIS FILE IS THE REASON A HAND-ROLLED PRIMITIVE IS ACCEPTABLE HERE
 *
 * `A-33` proposes `otplib`, and `A-33` is unusable: it sits in the contested `A-31`…`A-39` block
 * that is `BLK-09`, open, and the owner's to resolve. So the implementation is the alternative
 * `A-33`'s own row names — hand-rolled over `node:crypto` — and that row records the cost
 * accurately: *"a cryptographic primitive written in-house is a review liability"*.
 *
 * The liability is that nobody can tell whether it is right. RFC 6238 Appendix B answers exactly
 * that, by publishing the values a correct implementation produces. Every vector below is
 * transcribed from the RFC, not generated by running this code — a self-generated fixture would
 * prove only that the implementation agrees with itself, which is the failure mode being avoided.
 *
 *   RFC 6238, Appendix B — SHA-1, seed "12345678901234567890" (20 ASCII bytes), 8 digits.
 * ═══════════════════════════════════════════════════════════════════════════════════════════
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  TOTP_DIGITS,
  TOTP_DRIFT_STEPS,
  TOTP_SECRET_BYTES,
  TOTP_STEP_SECONDS,
  base32Encode,
  generateTotpSecret,
  hotp,
  provisioningUri,
  stepAt,
  totp,
  verifyTotp,
} from '../dist/iam/infrastructure/totp.adapter.js';

/** RFC 6238 Appendix B's SHA-1 seed, verbatim. */
const RFC_SEED = Buffer.from('12345678901234567890', 'ascii');

/** RFC 6238 Appendix B, the SHA-1 rows: [unix seconds, expected 8-digit TOTP]. */
const RFC_6238_VECTORS: readonly (readonly [number, string])[] = [
  [59, '94287082'],
  [1_111_111_109, '07081804'],
  [1_111_111_111, '14050471'],
  [1_234_567_890, '89005924'],
  [2_000_000_000, '69279037'],
  [20_000_000_000, '65353130'],
];

// ═══════════════════════════════════════════════════════════════════════════
// The vectors
// ═══════════════════════════════════════════════════════════════════════════

test('RFC 6238 Appendix B — every published SHA-1 vector reproduces exactly', () => {
  for (const [seconds, expected] of RFC_6238_VECTORS) {
    assert.equal(
      totp(RFC_SEED, seconds * 1000, 8),
      expected,
      `RFC 6238 says T=${String(seconds)} produces ${expected}`,
    );
  }
});

test('the last vector is the 32-bit truncation trap, and it is in the list on purpose', () => {
  // T=20000000000 exceeds 2^32 seconds, so its step counter overflows a 32-bit write. An
  // implementation using `writeUInt32BE` into the low half — the natural mistake — passes the
  // first five vectors and fails only this one. It is the reason the counter is a `BigInt`.
  assert.equal(totp(RFC_SEED, 20_000_000_000 * 1000, 8), '65353130');
  assert.equal(stepAt(20_000_000_000 * 1000), 666_666_666n);
});

test('RFC 4226 §5.3 — the truncation is taken from the LAST byte of the digest', () => {
  // The offset comes from `digest[19] & 0x0f`. Reading `digest[0]` instead produces a plausible
  // six-digit number for every input and matches no authenticator app on earth. The vectors above
  // already catch it; this states the property so the failure is legible when it happens.
  const counter = 1n;
  const first = hotp(RFC_SEED, counter, 8);
  assert.match(first, /^\d{8}$/);
  // RFC 4226 Appendix D, HOTP counter 1 with the same seed.
  assert.equal(first, '94287082');
});

// ═══════════════════════════════════════════════════════════════════════════
// The parameters §2.8 fixes
// ═══════════════════════════════════════════════════════════════════════════

test('Security.md §2.8 — 6 digits, 30-second step, ±1 drift, 160-bit secret', () => {
  assert.equal(TOTP_DIGITS, 6);
  assert.equal(TOTP_STEP_SECONDS, 30);
  assert.equal(TOTP_DRIFT_STEPS, 1);
  assert.equal(TOTP_SECRET_BYTES, 20);
  assert.equal(generateTotpSecret().length, 20);
});

test('two secrets from the generator are never the same', () => {
  // A constant secret would let anybody holding the code compute everybody's factor. Cheap to
  // assert, and the failure mode is total.
  const seen = new Set(Array.from({ length: 32 }, () => generateTotpSecret().toString('hex')));
  assert.equal(seen.size, 32);
});

// ═══════════════════════════════════════════════════════════════════════════
// Drift — exactly one step, in both directions
// ═══════════════════════════════════════════════════════════════════════════

const NOW = 1_700_000_000_000; // a fixed instant; the Clock port supplies it in production

test('a code from the previous or next step is accepted, two steps away is refused', () => {
  const secret = generateTotpSecret();
  const step = TOTP_STEP_SECONDS * 1000;

  for (const delta of [-1, 0, 1]) {
    const code = totp(secret, NOW + delta * step);
    assert.equal(
      verifyTotp(secret, code, NOW).valid,
      true,
      `a code ${String(delta)} step away should be accepted`,
    );
  }

  for (const delta of [-2, 2]) {
    const code = totp(secret, NOW + delta * step);
    assert.equal(
      verifyTotp(secret, code, NOW).valid,
      false,
      `a code ${String(delta)} steps away must be refused — §2.8 fixes the window at ±1`,
    );
  }
});

// ═══════════════════════════════════════════════════════════════════════════
// Replay — the half that is easy to omit
// ═══════════════════════════════════════════════════════════════════════════

test('§2.8 — a code from an already-accepted step is refused', () => {
  // ┌─ WITHOUT THIS, THE DRIFT WINDOW BECOMES A 90-SECOND CODE LIFETIME ─────────────────────────┐
  // │ The window exists for clock skew, not to give a code a longer life. A code read over        │
  // │ somebody's shoulder, or captured by a phishing page and replayed a minute later, works — and │
  // │ every test above still passes, because none of them submits the same code twice.            │
  // └───────────────────────────────────────────────────────────────────────────────────────────┘
  const secret = generateTotpSecret();
  const code = totp(secret, NOW);

  const first = verifyTotp(secret, code, NOW, null);
  assert.equal(first.valid, true);
  assert.notEqual(first.step, null);

  const replay = verifyTotp(secret, code, NOW, first.step);
  assert.equal(replay.valid, false, 'the same code verified twice');
});

test('an OLDER step is refused once a newer one has been accepted', () => {
  // The stored counter is a high-water mark, not an exact match. Accepting the previous step after
  // the current one has been used would reopen the window backwards.
  const secret = generateTotpSecret();
  const previous = totp(secret, NOW - TOTP_STEP_SECONDS * 1000);

  const currentStep = stepAt(NOW);
  assert.equal(verifyTotp(secret, previous, NOW, currentStep).valid, false);
});

test("the step RETURNED is the code's own step, not the newest in the window", () => {
  // Returning the current step for a code from the previous one would advance the high-water mark
  // past evidence, silently invalidating the code the user is about to submit for this step.
  const secret = generateTotpSecret();
  const previousCode = totp(secret, NOW - TOTP_STEP_SECONDS * 1000);

  const result = verifyTotp(secret, previousCode, NOW, null);
  assert.equal(result.valid, true);
  assert.equal(result.step, stepAt(NOW) - 1n);
});

// ═══════════════════════════════════════════════════════════════════════════
// Malformed input
// ═══════════════════════════════════════════════════════════════════════════

test('anything that is not six digits is refused without touching the secret', () => {
  const secret = generateTotpSecret();
  for (const submitted of ['', '12345', '1234567', 'abcdef', '12 456', '12345a', '  1234']) {
    assert.equal(verifyTotp(secret, submitted, NOW).valid, false, `${submitted} was accepted`);
  }
});

test('a code that is right for a DIFFERENT secret is refused', () => {
  const [mine, theirs] = [generateTotpSecret(), generateTotpSecret()];
  assert.equal(verifyTotp(mine, totp(theirs, NOW), NOW).valid, false);
});

// ═══════════════════════════════════════════════════════════════════════════
// The provisioning URI
// ═══════════════════════════════════════════════════════════════════════════

test('RFC 4648 base32, unpadded — checked against the RFC 4648 §10 vectors', () => {
  // Transcribed from RFC 4648's own test vectors, minus the padding the Key URI format omits.
  const vectors: readonly (readonly [string, string])[] = [
    ['', ''],
    ['f', 'MY'],
    ['fo', 'MZXQ'],
    ['foo', 'MZXW6'],
    ['foob', 'MZXW6YQ'],
    ['fooba', 'MZXW6YTB'],
    ['foobar', 'MZXW6YTBOI'],
  ];

  for (const [input, expected] of vectors) {
    assert.equal(base32Encode(Buffer.from(input, 'ascii')), expected, `base32("${input}")`);
  }
});

test('the otpauth URI carries the parameters an authenticator needs', () => {
  const uri = provisioningUri(RFC_SEED, 'ana@example.test');

  assert.match(uri, /^otpauth:\/\/totp\/GymMap:ana%40example\.test\?/);
  const params = new URLSearchParams(uri.slice(uri.indexOf('?') + 1));

  // The secret is base32 of the raw bytes — the one value an app cannot recover if it is wrong.
  assert.equal(params.get('secret'), base32Encode(RFC_SEED));
  assert.equal(params.get('algorithm'), 'SHA1');
  assert.equal(params.get('digits'), '6');
  assert.equal(params.get('period'), '30');
  // Both forms: the label prefix for older apps, the parameter for current ones.
  assert.equal(params.get('issuer'), 'GymMap');
});

test('an authenticator following the URI computes the code this verifier accepts', () => {
  // ┌─ THE ROUND TRIP, WHICH THE VECTORS DO NOT COVER ───────────────────────────────────────────┐
  // │ The vectors prove the algorithm. They do not prove that the secret we HAND OUT is the secret │
  // │ we verify against — a base32 bug would pass every vector above and make enrolment produce a  │
  // │ QR whose codes are always wrong, on every device, with no error anywhere.                    │
  // └───────────────────────────────────────────────────────────────────────────────────────────┘
  const secret = generateTotpSecret();
  const encoded = new URLSearchParams(
    provisioningUri(secret, 'ana@example.test').split('?')[1],
  ).get('secret');
  assert.ok(encoded);

  // Decode the base32 the way an authenticator app would, and confirm it is the same bytes.
  const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0;
  let value = 0;
  const out: number[] = [];
  for (const char of encoded) {
    value = (value << 5) | ALPHABET.indexOf(char);
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }

  assert.deepEqual(Buffer.from(out), secret, 'the QR encodes a different secret than we verify');
  assert.equal(verifyTotp(secret, totp(Buffer.from(out), NOW), NOW).valid, true);
});
