/**
 * Generates `tokens.css` from the TypeScript token modules — `DesignSystem.md` §2.3, §9.2.
 *
 * ┌─ THE CSS IS GENERATED BECAUSE TWO HAND-MAINTAINED COPIES DRIFT ─────────────────────────────┐
 * │ Every token exists twice: once as TypeScript (so the Tailwind preset, the density remap and  │
 * │ the contrast proof can read it) and once as a CSS custom property (so the browser can).      │
 * │ Hand-writing the second copy means a palette change lands in one and not the other, and the  │
 * │ symptom is one component keeping the old colour — which reads as a caching problem for about │
 * │ an hour.                                                                                      │
 * │                                                                                              │
 * │ `pnpm --filter @gymmap/ui tokens:check` fails if the committed CSS does not match what this  │
 * │ produces, so the drift is a CI failure rather than a mystery.                                 │
 * └──────────────────────────────────────────────────────────────────────────────────────────────┘
 *
 * `DM1` — one switch: `data-theme` on `<html>`. `prefers-color-scheme` is the DEFAULT and an
 * explicit `data-theme` is the OVERRIDE, and the override wins in both directions. A user who
 * chose light keeps light on a dark-mode OS; the naive `@media` block alone gets that wrong.
 */

import { palette } from './primitive/palette.ts';
import {
  CONTAINER_MAX,
  fontFamily,
  fontSize,
  fontWeight,
  measure,
  motion,
  radius,
  shadow,
  size,
  space,
  zIndex,
} from './primitive/scale.ts';
import { dark, light } from './semantic/index.ts';
import { semanticSpace } from './semantic/space.ts';
import { reducedMotionOverrides } from './semantic/misc.ts';
import { componentTokens, deskTokens } from './component/index.ts';
import { densities, DENSITIES } from './density/index.ts';

const PREFIX = '--gm-';

function declarations(entries: [string, string][], indent = '  '): string {
  return entries.map(([name, value]) => `${indent}${PREFIX}${name}: ${value};`).join('\n');
}

function primitiveDeclarations(): [string, string][] {
  const out: [string, string][] = [
    ['white', palette.white],
    ['black', palette.black],
  ];
  for (const [family, ramp] of Object.entries(palette)) {
    if (typeof ramp === 'string') continue;
    for (const [step, value] of Object.entries(ramp)) out.push([`${family}-${step}`, value]);
  }
  for (const [k, v] of Object.entries(space)) out.push([`space-${k}`, v]);
  for (const [k, v] of Object.entries(radius)) out.push([`radius-${k}`, v]);
  for (const [k, v] of Object.entries(size)) out.push([`size-${k}`, v]);
  for (const [k, v] of Object.entries(shadow)) out.push([`shadow-${k}`, v]);
  for (const [k, v] of Object.entries(zIndex)) out.push([`z-${k}`, v]);
  for (const [k, v] of Object.entries(motion.duration)) out.push([`motion-duration-${k}`, v]);
  for (const [k, v] of Object.entries(motion.ease)) out.push([`motion-ease-${k}`, v]);
  for (const [k, v] of Object.entries(measure)) out.push([`measure-${k}`, v]);
  for (const [k, v] of Object.entries(fontWeight)) out.push([`font-weight-${k}`, v]);
  for (const [k, v] of Object.entries(fontSize)) {
    const [sizeValue, meta] = v as [string, { lineHeight: string; letterSpacing: string }];
    out.push([`font-size-${k}`, sizeValue]);
    out.push([`line-height-${k}`, meta.lineHeight]);
    out.push([`tracking-${k}`, meta.letterSpacing]);
  }
  out.push(['font-sans', fontFamily.sans.map(quoteIfNeeded).join(', ')]);
  out.push(['font-mono', fontFamily.mono.map(quoteIfNeeded).join(', ')]);
  out.push(['container-max', CONTAINER_MAX]);
  return out;
}

/** A family name with a space needs quoting in a CSS font stack; a bare keyword must not be. */
function quoteIfNeeded(family: string): string {
  return /\s/.test(family) ? `'${family}'` : family;
}

export function generateTokensCss(): string {
  const colourLight = Object.entries(light) as [string, string][];
  const colourDark = Object.entries(dark) as [string, string][];
  const semantic = Object.entries(semanticSpace) as [string, string][];
  const component = [
    ...(Object.entries(componentTokens) as [string, string][]),
    ...(Object.entries(deskTokens) as [string, string][]),
  ];

  const densityBlocks = DENSITIES.map((mode) => {
    const entries = Object.entries(densities[mode]) as [string, string][];
    // `:root[data-density=…]` AND `[data-density=…]`, because §7.1 puts the attribute on the
    // nearest REGION root, not only on <html> — that is what lets the check-in desk run oversized
    // inside a compact app shell without a second document.
    return `:root[data-density='${mode}'],\n[data-density='${mode}'] {\n${declarations(entries)}\n}`;
  }).join('\n\n');

  return `/*
 * GENERATED by packages/ui/src/tokens/generate-css.ts — DO NOT EDIT.
 *
 * Regenerate:  pnpm --filter @gymmap/ui tokens:build
 * Verify:      pnpm --filter @gymmap/ui tokens:check
 *
 * DesignSystem.md §2.3. Every value here has a TypeScript source of truth; this file exists so a
 * browser can read the same values, and a hand-edit is the drift the check exists to catch.
 */

/* --- Tier 1 · primitive. Theme-independent. Never named by apps/**. ------------------------ */
:root {
${declarations(primitiveDeclarations())}
}

/* --- Tier 2 · semantic, non-colour. Theme-independent. ------------------------------------- */
:root {
${declarations(semantic)}
}

/* --- Tier 2 · semantic colour, light. The default when no preference is expressed. --------- */
:root,
:root[data-theme='light'] {
  /* ┌─ color-scheme IS THE ONLY WAY TO REACH THE PARTS CSS DOES NOT OWN ──────────────────┐
   * │ Scrollbars, form-control chrome, the canvas behind an overscroll, select popups and the      │
   * │ caret are drawn by the PLATFORM, not by this stylesheet. Without this declaration the        │
   * │ browser assumes light and draws a light-grey scrollbar down the right edge of a dark          │
   * │ console — which is what it did, on the page and on every scrollable panel, until this line.  │
   * │                                                                                              │
   * │ It sits beside the colour tokens rather than in an app stylesheet because it is a property    │
   * │ OF the theme: a theme that sets its surfaces and not its scrollbars is half a theme, and the  │
   * │ half it forgets is the one a screenshot shows.                                                │
   * └───────────────────────────────────────────────────────────────────────────────────────┘ */
  color-scheme: light;
${declarations(colourLight)}
}

/* --- Tier 2 · semantic colour, dark. --------------------------------------------------------
 * DM1: the OS preference is the default; an explicit data-theme is the override and wins in both
 * directions. The :not([data-theme='light']) is what makes "I chose light on a dark-mode OS"
 * work — without it the media query would silently win.
 */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${declarations(colourDark, '    ')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${declarations(colourDark)}
}

/* --- Tier 3 · component. Comfortable is the base; density remaps below. -------------------- */
:root {
${declarations(component)}
}

/* --- Density · §7. Size only, never colour, never meaning. --------------------------------- */
${densityBlocks}

/* --- Reduced motion · RM1. One place, no omissions. ----------------------------------------
 * 1ms rather than 0 so transitionend handlers still fire — code that waits for a transition
 * before removing a node would hang forever at 0, turning an accessibility preference into a
 * broken UI.
 */
@media (prefers-reduced-motion: reduce) {
  :root {
${declarations(Object.entries(reducedMotionOverrides) as [string, string][], '    ')}
  }

  *,
  *::before,
  *::after {
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 1ms !important;
    scroll-behavior: auto !important;
  }
}
`;
}
