/**
 * GENERATED by packages/config/scripts/isolation-coverage.mjs — DO NOT EDIT.
 *
 * Regenerate:  pnpm ci:isolation-coverage --write
 * Verify:      pnpm ci:isolation-coverage
 *
 * COMMITTED on purpose (IG-E). A regeneration that silently drops routes shows up as DELETED
 * LINES under CODEOWNERS review — which is the only way a shrinking isolation surface becomes
 * visible to a human. A gitignored inventory would let coverage fall without a diff.
 */

import type { Inventory } from './_inventory.ts';

export const GENERATED_INVENTORY: Inventory = {
  "generatedFrom": "openapi.json",
  "routes": [
    {
      "method": "GET",
      "path": "/v1/tenant/{tenantRef}/ping",
      "kind": "ITEM",
      "permission": "tenancy.ping.read",
      "expectedRefusal": 404,
      "needsTenantBId": true,
      "parameters": [
        "tenantRef"
      ]
    },
    {
      "method": "GET",
      "path": "/v1/tenant/ping",
      "kind": "COLLECTION",
      "permission": "tenancy.ping.read",
      "expectedRefusal": "EMPTY_SET",
      "needsTenantBId": false,
      "parameters": []
    }
  ],
  "otherAudiences": [
    {
      "method": "GET",
      "path": "/healthz",
      "audience": "PROBE"
    },
    {
      "method": "GET",
      "path": "/readyz",
      "audience": "PROBE"
    },
    {
      "method": "POST",
      "path": "/v1/auth/login",
      "audience": "PUBLIC"
    },
    {
      "method": "POST",
      "path": "/v1/auth/password/forgot",
      "audience": "PUBLIC"
    },
    {
      "method": "POST",
      "path": "/v1/auth/password/reset",
      "audience": "PUBLIC"
    },
    {
      "method": "POST",
      "path": "/v1/auth/register",
      "audience": "PUBLIC"
    }
  ]
} as const;
