-- migration: 20260810180000_expand_seed_reference_taxonomy
-- phase:            expand                     -- MG3
-- requirement:      BLK-21 RESOLVED, ADR-0042, NFR-DQ-06, FR-GYM-03, FR-SRCH-03,
--                   SeedStrategy.md SEP1, RD2, RD3, RD4, RD5, §3.7
-- tables:           amenities (59 rows), gym_categories (15 rows) — INSERT only
-- rls:              NONE — GLOBAL reference on the closed §1.3 exemption list
-- grants:           unchanged. G-REF minus the write half; rows are written by the migration role
-- append_only:      no UPDATE and no DELETE are granted to any application role
-- partitioned:      no
-- max_lock:         ROW EXCLUSIVE on two tables holding zero rows
-- rewrite:          none
-- est_duration:     < 40 ms                                               -- MG11
-- backfill_job:     none. This IS the data.
-- rollback:         DELETE both tables' rows by their derived ids. gyms.category_id and
--                   gym_amenities.amenity_id reference them, and both tables are empty
-- concurrent_steps: none
-- reviewers:        two, one schema owner, one product   -- MG8
-- docs:             docs/DECISION_LOG.md ADR-0042 · SeedStrategy.md §3.7 · PHASES.md BLK-21
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- GENERATED BY `pnpm ref:generate` FROM `prisma/reference/*.csv`. DO NOT EDIT BY HAND.
--
-- `RD4`: the data file is the source of truth and this file is its output. A hand edit here that
-- does not match the CSV fails `reference-data-drift` (§2.7), which hashes both.
--
-- ┌─ EVERY `key` IS §3.7 VERBATIM; ONLY THE DISPLAY LAYER IS NEW ────────────────────────────────┐
-- │ 59 amenity keys in six display groups (Facilities 16 · Equipment 16 · Classes 12 ·            │
-- │ Services 6 · Accessibility 6 · Hours 3) and 15 category keys, transcribed unchanged. What     │
-- │ `ADR-0042` adds is `name`, `icon`, `slug` and `sort_order` — the columns `Schema.md` §12.2     │
-- │ makes `NOT NULL` and no document fixes.                                                        │
-- │                                                                                              │
-- │ That asymmetry is the whole reason this was safe to decide: `RD2` derives every `id` from the │
-- │ KEY, so the ids are permanent and the display columns are editable through the `FR-ADMN-06`   │
-- │ path. `Epic_04.md` line 349 says so itself — *"retrofitting terms is cheap, retrofitting ids  │
-- │ is not"*.                                                                                       │
-- └──────────────────────────────────────────────────────────────────────────────────────────────┘
--
-- ┌─ NO `ON CONFLICT` — `RD5` ───────────────────────────────────────────────────────────────────┐
-- │ A plain INSERT, allowed to fail loudly. Under forward-only migrations a duplicate can only    │
-- │ mean this ran twice, which is itself the defect. Note this points the OPPOSITE way to `PM-9`'s │
-- │ `IF NOT EXISTS`: that rule is about DDL being re-appliable, this one is about DML being loud. │
-- └──────────────────────────────────────────────────────────────────────────────────────────────┘
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

SET LOCAL lock_timeout       = '5s';    -- PM-8. first statement, always
SET LOCAL statement_timeout  = '300s';  -- PM-8. second statement, always


-- amenities: 59 row(s), generated from amenities.csv
INSERT INTO amenities (id, key, name, icon, display_group, sort_order) VALUES
  ('9c8817d4-eeb0-5f7a-9d36-8e350e8785ed', 'AEROBICS', 'Aerobics', 'activity', 'Classes', '41'),
  ('674558aa-8902-5b16-9fcf-edee356e2308', 'AIR_CONDITIONING', 'Air conditioning', 'air-vent', 'Facilities', '10'),
  ('33d51f7d-965c-51c6-bae6-fa40f5d649a6', 'BODY_COMPOSITION_ANALYSIS', 'Body composition', 'percent', 'Services', '48'),
  ('5692a4db-befd-551b-9cc9-510e7d242cc5', 'BOXING_BAG', 'Boxing bags', 'cylinder', 'Equipment', '25'),
  ('637f7f8c-8a08-5b6e-b777-9410a7f3b4bb', 'CABLE_CROSSOVER', 'Cable crossover', 'cable', 'Equipment', '29'),
  ('b2a57bd2-840f-5e23-8b0b-8aadf1724090', 'CAFE', 'Cafe', 'coffee', 'Facilities', '16'),
  ('c5def608-b0e1-578b-90b9-7953cfa15815', 'CARDIO_ZONE', 'Cardio zone', 'heart-pulse', 'Equipment', '19'),
  ('bb77cfe1-2a67-52ce-a44f-69c667348962', 'CHANGING_ROOM', 'Changing room', 'shirt', 'Facilities', '57'),
  ('98daa000-4734-5897-a659-c6e0c6d56a66', 'CHILDCARE', 'Childcare', 'baby', 'Accessibility', '53'),
  ('100d35e1-ed87-5473-9087-7637415d979b', 'CROSSFIT_CLASS', 'CrossFit classes', 'timer', 'Classes', '35'),
  ('ef37c3fc-881e-5fb0-9585-0f4873198e3f', 'CROSSFIT_RIG', 'CrossFit rig', 'frame', 'Equipment', '22'),
  ('987057dd-9598-5c27-aa1b-63d712911538', 'DANCE_FITNESS', 'Dance fitness', 'disc-3', 'Classes', '44'),
  ('4146ad7b-870c-549c-b9d1-c4620b254bce', 'DIET_CONSULTATION', 'Diet consultation', 'salad', 'Services', '47'),
  ('2f771e40-9bd7-58a6-bf0b-2d427bf32b20', 'DRINKING_WATER_RO', 'RO drinking water', 'glass-water', 'Facilities', '8'),
  ('74a22e77-68a2-570f-9a46-9d122897a7a9', 'EARLY_MORNING_OPENING', 'Early opening', 'sunrise', 'Hours', '54'),
  ('e710f735-bb0e-599c-91d6-ff43861da460', 'ELLIPTICAL', 'Ellipticals', 'orbit', 'Equipment', '31'),
  ('f4067a94-f2c9-54dc-bb12-64b5b292b9f1', 'FREE_WEIGHTS', 'Free weights', 'weight', 'Equipment', '18'),
  ('4a5bfcdd-d2a6-56f6-b0a0-9d3b851d350e', 'FUNCTIONAL_TRAINING_ZONE', 'Functional zone', 'move', 'Equipment', '21'),
  ('151f6bab-0d00-5e52-8ce9-5664c0b6f4a4', 'GROUND_FLOOR', 'Ground floor', 'door-open', 'Accessibility', '51'),
  ('ef4ad867-749e-5e83-9c67-7392a21e7e0a', 'GROUP_CLASSES_INCLUDED', 'Group classes', 'calendar-days', 'Services', '11'),
  ('68ecbb05-074c-5125-8f39-31dbae177858', 'HIIT', 'HIIT', 'zap', 'Classes', '36'),
  ('17c07f67-841e-51a9-8908-8019177cdb95', 'JUICE_BAR', 'Juice bar', 'cup-soda', 'Facilities', '58'),
  ('e7777ea7-ed1b-50d3-9496-52db4494ff44', 'KICKBOXING', 'Kickboxing', 'target', 'Classes', '43'),
  ('1912a3a1-20d4-5a90-907a-f0d7b388b755', 'LATE_NIGHT_CLOSING', 'Late closing', 'moon-star', 'Hours', '55'),
  ('803c5bd9-5268-5243-97fa-0cf4ed1d86b1', 'LIFT_ACCESS', 'Lift access', 'arrow-up-down', 'Accessibility', '50'),
  ('46b3c15c-e786-55fa-ac3f-7b318a78c495', 'LOCKER_ROOM', 'Lockers', 'vault', 'Facilities', '14'),
  ('e3c0149f-45a9-5259-bf16-a6f446847b7b', 'MEDITATION', 'Meditation', 'brain', 'Classes', '45'),
  ('c7d236b8-573a-590f-90e6-a95aa598a9bc', 'MMA', 'MMA', 'swords', 'Classes', '42'),
  ('c0316512-8bbc-57fa-b6f4-21912502b261', 'OLYMPIC_PLATFORM', 'Olympic platform', 'rectangle-horizontal', 'Equipment', '23'),
  ('7243bb6c-8814-59e5-a29f-279e9f5408c0', 'OPEN_24_HOURS', 'Open 24 hours', 'clock-12', 'Hours', '1'),
  ('0289850b-ce71-5332-9160-ec5aa15b5c0c', 'PARKING_CAR', 'Car parking', 'car', 'Facilities', '2'),
  ('229c30bc-970d-51c0-a8cc-3b59e3417b49', 'PARKING_TWO_WHEELER', 'Two-wheeler parking', 'scooter', 'Facilities', '3'),
  ('ffc56efe-fbec-5663-9cb5-556f3ea7ac2f', 'PERSONAL_TRAINING', 'Personal training', 'dumbbell', 'Services', '9'),
  ('ff66f1f2-9106-5140-9373-79c36ea5698c', 'PHYSIOTHERAPY', 'Physiotherapy', 'stethoscope', 'Services', '46'),
  ('712d2bfc-218e-52fb-b3ef-6b11f8c4697a', 'PILATES', 'Pilates', 'stretch-horizontal', 'Classes', '39'),
  ('b7f9dd44-4457-5c93-92ab-e1013d9084e6', 'POWER_BACKUP', 'Power backup', 'battery-charging', 'Facilities', '7'),
  ('6dd08e34-1073-5f59-b4c2-9045d94581d6', 'PRO_SHOP', 'Pro shop', 'shopping-bag', 'Facilities', '59'),
  ('55c221f4-c1e0-564c-a17c-a47d262b6188', 'RECOVERY_ZONE', 'Recovery zone', 'armchair', 'Equipment', '26'),
  ('bdb782b0-de59-5416-88cc-afeb1a671058', 'RESISTANCE_MACHINES', 'Resistance machines', 'layers', 'Equipment', '20'),
  ('b08fd158-e4eb-5ea3-a71b-b0892927adfd', 'ROWING_MACHINE', 'Rowing machines', 'sailboat', 'Equipment', '32'),
  ('d649b51c-c806-5140-8f5c-0d864a2af30d', 'SAUNA', 'Sauna', 'flame', 'Facilities', '12'),
  ('f2c3209c-af29-573e-a165-33c3e45c605c', 'SHOWERS', 'Showers', 'shower-head', 'Facilities', '15'),
  ('590e9416-c783-5e6d-933e-9c3752314154', 'SMITH_MACHINE', 'Smith machine', 'columns-2', 'Equipment', '28'),
  ('cb62ea89-5f66-5f0a-a1d0-0da12a85caf6', 'SPINNING', 'Spinning', 'gauge', 'Classes', '37'),
  ('98dfc559-b69b-58ce-a9e9-ae8baa1a1865', 'SPIN_BIKES', 'Spin bikes', 'bike', 'Equipment', '33'),
  ('9b92973b-51a2-5f9b-87b4-7ee568e57a9a', 'STEAM_ROOM', 'Steam room', 'droplets', 'Facilities', '13'),
  ('39689b29-aeb9-562a-98dc-7e86d0b09dd2', 'STRENGTH_CLASS', 'Strength classes', 'biceps-flexed', 'Classes', '40'),
  ('9e5f7a3a-2afe-5ca1-9d8a-101bf8e81aee', 'STRETCHING_ZONE', 'Stretching zone', 'person-standing', 'Equipment', '27'),
  ('2e4f33d6-a94a-5145-aa77-eebe3b8f2e82', 'SWIMMING_POOL', 'Swimming pool', 'waves', 'Facilities', '4'),
  ('262bcff1-e3b7-5426-8742-70fbf40401a7', 'TOWEL_SERVICE', 'Towel service', 'concierge-bell', 'Facilities', '56'),
  ('17c39fbf-c1bb-5d89-a895-ec98b6e47f75', 'TREADMILL', 'Treadmills', 'footprints', 'Equipment', '30'),
  ('6308324d-2be8-50eb-979b-667f43df9aa9', 'TRIAL_SESSION', 'Trial session', 'gift', 'Services', '6'),
  ('00232afb-ed15-5cbd-b8a3-4c0d9f7f11c8', 'TURF_AREA', 'Turf area', 'land-plot', 'Equipment', '24'),
  ('24b249e4-c600-5a24-ae28-e1a0cee13a22', 'WHEELCHAIR_ACCESS', 'Wheelchair access', 'accessibility', 'Accessibility', '49'),
  ('7427527e-c365-555c-9460-12a94ae4701e', 'WIFI', 'Wi-Fi', 'wifi', 'Facilities', '17'),
  ('18db2f1b-6029-547e-af05-e26ad3d1f8cb', 'WOMEN_ONLY_HOURS', 'Women-only hours', 'venus', 'Accessibility', '5'),
  ('1fb1fa8c-0b37-5846-87c2-4e4305ec42df', 'WOMEN_TRAINER_AVAILABLE', 'Women trainers', 'user-round-check', 'Accessibility', '52'),
  ('d9a1546c-6043-509c-b1bf-78370fe2b902', 'YOGA', 'Yoga', 'flower-2', 'Classes', '34'),
  ('2cae0eff-3e60-51c9-9e0b-4d776579babb', 'ZUMBA', 'Zumba', 'music-4', 'Classes', '38');

-- gym_categories: 15 row(s), generated from gym-categories.csv
INSERT INTO gym_categories (id, key, name, slug, sort_order) VALUES
  ('bb702941-bd85-5f9c-9be9-3e73b80b6e83', 'BOXING_MMA', 'Boxing & MMA', 'boxing-mma', '7'),
  ('0aebf658-5479-5565-a75a-7d08b4d1c415', 'BUDGET_GYM', 'Budget gym', 'budget-gym', '13'),
  ('5050ddbc-36bc-5375-8033-9ca9c10cafa8', 'CROSSFIT_BOX', 'CrossFit box', 'crossfit-box', '3'),
  ('5e62fa11-57ef-5415-95c6-ecb98a69ff45', 'DANCE_STUDIO', 'Dance studio', 'dance-studio', '8'),
  ('fe1ec8a2-37e2-5f27-8640-8eb745285327', 'FITNESS_STUDIO', 'Fitness studio', 'fitness-studio', '2'),
  ('190f06a8-26ef-5e88-9c8a-a368c4893448', 'GYM', 'Gym', 'gym', '1'),
  ('cdb84538-a316-5640-9df8-2e787f3e377d', 'MARTIAL_ARTS', 'Martial arts', 'martial-arts', '6'),
  ('88f7f372-56a3-55e8-a186-7b9d4786d953', 'PILATES_STUDIO', 'Pilates studio', 'pilates-studio', '5'),
  ('febb453d-a6c4-5b86-94ee-700ca61273ba', 'PREMIUM_CLUB', 'Premium club', 'premium-club', '12'),
  ('f74e5ed6-edc7-5584-8d17-0dea7df660d0', 'PT_STUDIO', 'Personal training studio', 'personal-training-studio', '14'),
  ('14d98d34-1de3-5272-a1b2-e564d9723f16', 'SPORTS_COMPLEX', 'Sports complex', 'sports-complex', '10'),
  ('5008e2c2-fb49-533e-b3d2-02146be03724', 'SWIMMING_ACADEMY', 'Swimming academy', 'swimming-academy', '9'),
  ('d2de3974-b5a0-52f2-999d-8c5e9294157f', 'WELLNESS_CENTRE', 'Wellness centre', 'wellness-centre', '15'),
  ('f4daaffc-6b3e-5564-85db-f64c9e76c2a7', 'WOMEN_ONLY_GYM', 'Women-only gym', 'women-only-gym', '11'),
  ('d2972692-541b-58cb-9b61-62f92977a2fd', 'YOGA_STUDIO', 'Yoga studio', 'yoga-studio', '4');
